# Generated by Django 5.2.13 on 2026-04-22 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyBriefConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('schedule_day', models.IntegerField(default=1, help_text='0=Mon..6=Sun')),
                ('schedule_hour', models.IntegerField(default=7)),
                ('timezone', models.CharField(default='Europe/Prague', max_length=64)),
                ('sections_enabled', models.JSONField(blank=True, default=list, help_text='List of section keys to include')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyBriefReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.JSONField(default=dict)),
                ('html_body', models.TextField(blank=True)),
                ('plain_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('period_start', 'period_end')},
            },
        ),
    ]
