"""Trello REST API v1 client.

Auth: API key + token. Both are passed as query string parameters on
every request (Trello convention). The token is generated by the user
via https://trello.com/app-key + the "Token" link below the API key.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from apps.data_access.models import Credential, Integration

logger = logging.getLogger(__name__)

BASE_URL = "https://api.trello.com/1"
DEFAULT_TIMEOUT = 20.0


def _credentials(integration: Integration) -> tuple[str, str]:
    cred = Credential.objects.filter(integration=integration).first()
    if cred is None:
        raise ValueError("Trello integration has no credential")
    tokens = cred.get_tokens()
    api_key = tokens.get("api_key")
    token = tokens.get("token")
    if not api_key or not token:
        raise ValueError("Trello credential missing api_key/token")
    return str(api_key), str(token)


class TrelloClient:
    def __init__(
        self,
        integration: Integration,
        *,
        http_client: httpx.Client | None = None,
    ) -> None:
        self._api_key, self._token = _credentials(integration)
        self._client = http_client or httpx.Client(
            base_url=BASE_URL,
            timeout=DEFAULT_TIMEOUT,
            headers={"Accept": "application/json"},
        )

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> TrelloClient:
        return self

    def __exit__(self, *_: Any) -> None:
        self.close()

    def _get(self, path: str, params: dict[str, Any] | None = None) -> Any:
        merged = {"key": self._api_key, "token": self._token, **(params or {})}
        resp = self._client.get(path, params=merged)
        resp.raise_for_status()
        return resp.json()

    def me(self) -> dict[str, Any]:
        return dict(self._get("/members/me"))

    def list_boards(self) -> list[dict[str, Any]]:
        return list(self._get("/members/me/boards", {"fields": "name,closed,url,dateLastActivity"}))

    def list_lists(self, board_id: str) -> list[dict[str, Any]]:
        return list(
            self._get(f"/boards/{board_id}/lists", {"fields": "name,closed,pos"})
        )

    def list_cards(self, board_id: str, since_iso: str | None = None) -> list[dict[str, Any]]:
        params: dict[str, Any] = {
            "fields": "name,closed,due,dueComplete,idList,idMembers,labels,dateLastActivity,url",
        }
        if since_iso:
            params["since"] = since_iso
        return list(self._get(f"/boards/{board_id}/cards", params))

    def list_actions(
        self, board_id: str, since_iso: str | None = None, limit: int = 1000
    ) -> list[dict[str, Any]]:
        params: dict[str, Any] = {"limit": min(limit, 1000)}
        if since_iso:
            params["since"] = since_iso
        return list(self._get(f"/boards/{board_id}/actions", params))
