# Generated by Django 5.2.13 on 2026-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit', models.CharField(default='CZK', max_length=20)),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end', 'name'],
                'indexes': [models.Index(fields=['name', '-period_end'], name='data_access_name_7de0b0_idx')],
            },
        ),
    ]
