# Generated by Django 5.2.13 on 2026-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0002_manualkpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('google_workspace', 'Google Workspace'), ('slack', 'Slack')], max_length=40),
        ),
    ]
