# Generated by Django 5.2.13 on 2026-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_access', '0005_knowledge_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_access_knowledgechunk',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='workspacedocument',
            new_name='data_access_source_bc69a0_idx',
            old_name='data_access_doc_src_st_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacedocument',
            new_name='data_access_owner_e_c6d2fb_idx',
            old_name='data_access_doc_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='workspacedocument',
            new_name='data_access_modifie_651eb5_idx',
            old_name='data_access_doc_mod_idx',
        ),
        migrations.AlterField(
            model_name='ingestioncursor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('google_workspace', 'Google Workspace (per-user OAuth)'), ('google_workspace_dwd', 'Google Workspace (Domain-Wide Delegation)'), ('slack', 'Slack'), ('smartemailing', 'SmartEmailing'), ('pipedrive', 'Pipedrive'), ('canva', 'Canva (MCP)'), ('trello', 'Trello'), ('raynet', 'Raynet CRM'), ('caflou', 'Caflou'), ('ecomail', 'Ecomail'), ('fapi', 'FAPI'), ('microsoft365', 'Microsoft 365 (mail + Teams + OneDrive)'), ('salesforce', 'Salesforce'), ('asana', 'Asana'), ('basecamp', 'Basecamp'), ('mailchimp', 'Mailchimp'), ('calendly', 'Calendly'), ('hubspot', 'HubSpot'), ('jira', 'Jira (Atlassian)'), ('notion', 'Notion (MCP)'), ('dropbox', 'Dropbox (MCP)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='workspacedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
