# Generated by Django 5.2.13 on 2026-05-13 04:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_addonactivation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('org_type', models.CharField(choices=[('client', 'Klient SCB'), ('prospect', 'Prospekt'), ('vendor', 'Dodavatel'), ('partner', 'Partner'), ('internal', 'Interní (SCB)'), ('other', 'Jiné')], default='client', max_length=32)),
                ('ico', models.CharField(blank=True, db_index=True, max_length=32)),
                ('dic', models.CharField(blank=True, db_index=True, max_length=32)),
                ('primary_domain', models.CharField(blank=True, db_index=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='identity.organization')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('slack_id', 'Slack user ID'), ('slack_handle', 'Slack handle'), ('pipedrive_person_id', 'Pipedrive person ID'), ('pipedrive_org_id', 'Pipedrive organization ID'), ('fapi_customer_id', 'FAPI customer ID'), ('br_user_id', 'Business Review user ID'), ('zoom_email', 'Zoom email'), ('google_id', 'Google account ID'), ('linkedin_url', 'LinkedIn URL'), ('ico', 'IČO'), ('dic', 'DIČ'), ('domain', 'Email/web domain')], max_length=32)),
                ('identity_value', models.CharField(max_length=512)),
                ('source_system', models.CharField(choices=[('manual', 'Manual entry'), ('pipedrive', 'Pipedrive'), ('fapi', 'FAPI'), ('br', 'Business Review'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('google', 'Google Workspace'), ('microsoft365', 'Microsoft 365'), ('merk', 'Merk'), ('ai_match', 'AI matcher')], default='manual', max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=1.0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='identity.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('primary_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('person_type', models.CharField(choices=[('client', 'Klient'), ('team', 'Interní tým SCB'), ('contact', 'Kontakt'), ('vendor', 'Dodavatel'), ('prospect', 'Prospekt'), ('other', 'Jiné')], default='contact', max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='identity.person')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('slack_id', 'Slack user ID'), ('slack_handle', 'Slack handle'), ('pipedrive_person_id', 'Pipedrive person ID'), ('pipedrive_org_id', 'Pipedrive organization ID'), ('fapi_customer_id', 'FAPI customer ID'), ('br_user_id', 'Business Review user ID'), ('zoom_email', 'Zoom email'), ('google_id', 'Google account ID'), ('linkedin_url', 'LinkedIn URL'), ('ico', 'IČO'), ('dic', 'DIČ'), ('domain', 'Email/web domain')], max_length=32)),
                ('identity_value', models.CharField(max_length=512)),
                ('source_system', models.CharField(choices=[('manual', 'Manual entry'), ('pipedrive', 'Pipedrive'), ('fapi', 'FAPI'), ('br', 'Business Review'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('google', 'Google Workspace'), ('microsoft365', 'Microsoft 365'), ('merk', 'Merk'), ('ai_match', 'AI matcher')], default='manual', max_length=32)),
                ('verified', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=1.0)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='identity.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonMergeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_a', models.UUIDField()),
                ('person_b', models.UUIDField()),
                ('matched_by', models.CharField(choices=[('email_exact', 'Email exact match'), ('identity_exact', 'Identity exact match'), ('name_domain_fuzzy', 'Name + domain fuzzy'), ('name_company_fuzzy', 'Name + company fuzzy'), ('ai_match', 'AI matcher'), ('slack_lookup', 'Slack lookupByEmail'), ('manual', 'Manual')], max_length=32)),
                ('confidence', models.FloatField(default=1.0)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('undo_token', models.UUIDField(default=uuid.uuid4)),
                ('matched_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('merged_into', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_events', to='identity.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonOrganizationRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('coo', 'COO'), ('cfo', 'CFO'), ('cto', 'CTO'), ('owner', 'Majitel'), ('employee', 'Zaměstnanec'), ('board', 'Člen představenstva'), ('contact', 'Kontaktní osoba'), ('coach', 'Kouč (SCB)'), ('sales', 'Sales (SCB)'), ('other', 'Jiné')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source_system', models.CharField(choices=[('manual', 'Manual entry'), ('pipedrive', 'Pipedrive'), ('fapi', 'FAPI'), ('br', 'Business Review'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('google', 'Google Workspace'), ('microsoft365', 'Microsoft 365'), ('merk', 'Merk'), ('ai_match', 'AI matcher')], default='manual', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='identity.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='identity.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='identity_or_org_typ_8d9c29_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='identity_or_name_ec1e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationidentity',
            index=models.Index(fields=['identity_type'], name='identity_or_identit_69fbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationidentity',
            index=models.Index(fields=['identity_value'], name='identity_or_identit_7a9f93_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationidentity',
            constraint=models.UniqueConstraint(fields=('identity_type', 'identity_value'), name='uniq_org_identity_type_value'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type'], name='identity_pe_person__3c8552_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['display_name'], name='identity_pe_display_e94e54_idx'),
        ),
        migrations.AddIndex(
            model_name='personidentity',
            index=models.Index(fields=['identity_type'], name='identity_pe_identit_aaade3_idx'),
        ),
        migrations.AddIndex(
            model_name='personidentity',
            index=models.Index(fields=['identity_value'], name='identity_pe_identit_e97412_idx'),
        ),
        migrations.AddConstraint(
            model_name='personidentity',
            constraint=models.UniqueConstraint(fields=('identity_type', 'identity_value'), name='uniq_identity_type_value'),
        ),
        migrations.AddIndex(
            model_name='personorganizationrole',
            index=models.Index(fields=['role'], name='identity_pe_role_d88c86_idx'),
        ),
        migrations.AddIndex(
            model_name='personorganizationrole',
            index=models.Index(fields=['organization', 'role'], name='identity_pe_organiz_6d11bf_idx'),
        ),
    ]
