# Generated by Django 5.2.13 on 2026-05-06 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('entity_count', models.IntegerField(default=0)),
                ('edge_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('message', 'Message'), ('text', 'Text'), ('json', 'JSON')], default='message', max_length=32)),
                ('source_description', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('graphiti_episode_uuid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('reference_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reference_time'],
                'indexes': [models.Index(fields=['source', '-reference_time'], name='memory_know_source_b68f91_idx')],
            },
        ),
    ]
