# Generated by Django 5.2.13 on 2026-04-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('cost_czk', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cached', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_llmusa_tenant__4472f4_idx'), models.Index(fields=['model', '-created_at'], name='core_llmusa_model_994b2c_idx')],
            },
        ),
    ]
