# Generated by Django 5.2.13 on 2026-04-22 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_llmusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit_czk', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('per_conversation_limit_czk', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('current_month_spent_czk', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('period_start', models.DateField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('prompt_hash', models.CharField(max_length=64)),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_compli_tenant__c84fe8_idx')],
            },
        ),
    ]
