# Generated by Django 5.2.13 on 2026-04-22 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tenantbudget_compliancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(db_index=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_activations', to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'addon_name'], name='core_addona_tenant__8bed2c_idx')],
                'unique_together': {('tenant', 'addon_name')},
            },
        ),
    ]
