# Generated by Django 5.2.13 on 2026-05-13 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors_framework', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScbMerkCompany',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ico', models.CharField(db_index=True, max_length=32, unique=True)),
                ('dic', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('nace_codes', models.JSONField(blank=True, default=list)),
                ('employee_count_range', models.CharField(blank=True, max_length=32)),
                ('turnover_range', models.CharField(blank=True, max_length=32)),
                ('last_known_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('turnover_year', models.IntegerField(blank=True, null=True)),
                ('profit_last', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('profit_year', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, max_length=16)),
                ('rating_breakdown', models.JSONField(blank=True, default=dict)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('contacts_summary', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['source_system', 'source_id'], name='connectors__source__323d2b_idx'), models.Index(fields=['ico'], name='connectors__ico_197c41_idx')],
            },
        ),
    ]
