# Generated by Django 5.2.13 on 2026-05-06 06:01

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_memoryembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('insight', 'Insight'), ('brief', 'Brief'), ('chat', 'Chat'), ('document', 'Document')], db_index=True, max_length=32)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agents_memoryembedding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(db_index=True, max_length=64)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('trace_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_type', '-created_at'], name='agents_agen_agent_t_c44231_idx'), models.Index(fields=['session_id', '-created_at'], name='agents_agen_session_f88024_idx')],
            },
        ),
    ]
