# Generated by Django 5.2.13 on 2026-05-13 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors_framework', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScbFapiCustomer',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fapi_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ico', models.CharField(blank=True, db_index=True, max_length=32)),
                ('dic', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('fapi_created_at', models.DateTimeField(blank=True, null=True)),
                ('fapi_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScbFapiInvoice',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fapi_id', models.CharField(max_length=64, unique=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='CZK', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('fapi_created_at', models.DateTimeField(blank=True, null=True)),
                ('fapi_updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='connectors_fapi.scbfapicustomer')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='scbfapicustomer',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__cde75a_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapicustomer',
            index=models.Index(fields=['fapi_id'], name='connectors__fapi_id_83bc47_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapicustomer',
            index=models.Index(fields=['ico'], name='connectors__ico_3405bc_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapiinvoice',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__6135f1_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapiinvoice',
            index=models.Index(fields=['fapi_id'], name='connectors__fapi_id_95f0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapiinvoice',
            index=models.Index(fields=['status'], name='connectors__status_1b89b7_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapiinvoice',
            index=models.Index(fields=['organization', 'status'], name='connectors__organiz_0b3025_idx'),
        ),
        migrations.AddIndex(
            model_name='scbfapiinvoice',
            index=models.Index(fields=['due_at'], name='connectors__due_at_fc0605_idx'),
        ),
    ]
