# Generated by Django 5.2.13 on 2026-05-13 05:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors_framework', '0001_initial'),
        ('data_access', '0006_knowledgechunk_and_more'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScbSlackWorkspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_workspace', to='data_access.integration')),
            ],
        ),
        migrations.CreateModel(
            name='ScbSlackChannel',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slack_channel_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('purpose', models.TextField(blank=True)),
                ('topic', models.TextField(blank=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_tracked', models.BooleanField(db_index=True, default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('last_message_synced_ts', models.CharField(blank=True, max_length=32)),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='connectors_slack.scbslackworkspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScbSlackMessage',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.CharField(max_length=32)),
                ('thread_ts', models.CharField(blank=True, max_length=32)),
                ('slack_user_id', models.CharField(blank=True, max_length=32)),
                ('text', models.TextField(blank=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('reactions', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='connectors_slack.scbslackchannel')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['source_system', 'source_id'], name='connectors__source__d44615_idx'), models.Index(fields=['channel', '-posted_at'], name='connectors__channel_a4c245_idx'), models.Index(fields=['thread_ts'], name='connectors__thread__9ee99b_idx')],
                'constraints': [models.UniqueConstraint(fields=('channel', 'ts'), name='uniq_slack_channel_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='scbslackchannel',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__c8658c_idx'),
        ),
        migrations.AddIndex(
            model_name='scbslackchannel',
            index=models.Index(fields=['slack_channel_id'], name='connectors__slack_c_df0088_idx'),
        ),
    ]
