# Generated by Django 5.2.13 on 2026-05-13 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_access', '0006_knowledgechunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('mode', models.CharField(choices=[('init', 'Initial backfill'), ('incremental', 'Incremental'), ('reconcile', 'Full reconcile'), ('webhook', 'Webhook-triggered'), ('manual', 'Manual trigger')], default='incremental', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('resource', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cursor_before', models.CharField(blank=True, max_length=255)),
                ('cursor_after', models.CharField(blank=True, max_length=255)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='data_access.integration')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['provider', '-started_at'], name='connectors__provide_835cc0_idx'), models.Index(fields=['status', '-started_at'], name='connectors__status_ec5a64_idx')],
            },
        ),
    ]
