# Generated by Django 5.2.13 on 2026-05-13 05:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connectors_framework', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScbPipedriveDeal',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('pipedrive_org_id', models.IntegerField(blank=True, null=True)),
                ('pipedrive_person_id', models.IntegerField(blank=True, null=True)),
                ('owner_pipedrive_user_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost'), ('deleted', 'Deleted')], default='open', max_length=16)),
                ('stage_id', models.IntegerField(blank=True, null=True)),
                ('pipeline_id', models.IntegerField(blank=True, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('lost_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=255)),
                ('pipedrive_created_at', models.DateTimeField(blank=True, null=True)),
                ('pipedrive_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScbPipedriveActivity',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('pipedrive_deal_id', models.IntegerField(blank=True, null=True)),
                ('pipedrive_org_id', models.IntegerField(blank=True, null=True)),
                ('pipedrive_person_id', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('task', 'Task'), ('lunch', 'Lunch'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=16)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('note', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('owner_pipedrive_user_id', models.IntegerField(blank=True, null=True)),
                ('pipedrive_created_at', models.DateTimeField(blank=True, null=True)),
                ('pipedrive_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='connectors_pipedrive.scbpipedrivedeal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScbPipedriveOrganization',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('owner_pipedrive_user_id', models.IntegerField(blank=True, null=True)),
                ('visible_to', models.IntegerField(blank=True, null=True)),
                ('pipedrive_created_at', models.DateTimeField(blank=True, null=True)),
                ('pipedrive_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScbPipedrivePerson',
            fields=[
                ('source_system', models.CharField(db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('source_synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipedrive_id', models.IntegerField(unique=True)),
                ('pipedrive_org_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('primary_phone', models.CharField(blank=True, max_length=64)),
                ('owner_pipedrive_user_id', models.IntegerField(blank=True, null=True)),
                ('pipedrive_created_at', models.DateTimeField(blank=True, null=True)),
                ('pipedrive_updated_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.organization')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='connectors_framework.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='scbpipedrivedeal',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__5acc8d_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedrivedeal',
            index=models.Index(fields=['pipedrive_id'], name='connectors__pipedri_f29187_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedrivedeal',
            index=models.Index(fields=['status'], name='connectors__status_367352_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedrivedeal',
            index=models.Index(fields=['organization', 'status'], name='connectors__organiz_9fdccb_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveactivity',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__1bdefc_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveactivity',
            index=models.Index(fields=['pipedrive_id'], name='connectors__pipedri_c90c89_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveactivity',
            index=models.Index(fields=['due_date'], name='connectors__due_dat_92b84e_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveactivity',
            index=models.Index(fields=['done'], name='connectors__done_915b14_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveorganization',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__cb2404_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveorganization',
            index=models.Index(fields=['pipedrive_id'], name='connectors__pipedri_133414_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveperson',
            index=models.Index(fields=['source_system', 'source_id'], name='connectors__source__1211ae_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveperson',
            index=models.Index(fields=['pipedrive_id'], name='connectors__pipedri_0dd388_idx'),
        ),
        migrations.AddIndex(
            model_name='scbpipedriveperson',
            index=models.Index(fields=['primary_email'], name='connectors__primary_b5d2bf_idx'),
        ),
    ]
